---
title: "git_01"
author: "Cadence Gorden"
date: "Fall semester"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
# Build a Poem with commits to different branches
Our project will be done using a sequence of save and commits and branch actions.
<!-- Do not modify or change any text in "!--" bracketed areas such as this --- these are instructions to
you, if you change any of this the git program will notice it and compromise your git merging strategy !-->

## First Verse 
<!--Put the first five lines of a poem by Lewis Carrol in this section!-->
And cannot pleasures, while they last,  
Be actual unless, when past,  
They leave us shuddering and aghast,  
With anguish smarting?  
And cannot friends be firm and fast,  

## Second Verse
<!--Put the first five lines of a poem by Robert Frost here!-->
Something there is that doesn’t love a wall,  
That sends the frozen-ground-swell under it,  
And spills the upper boulders in the sun;  
And makes gaps even two can pass abreast.  
The work of hunters is another thing:  

## Third Verse
<!--Put the first two verses of The Walrus and the Carpenter here!-->
The sun was shining on the sea,  
Shining with all his might:  
He did his very best to make  
The billows smooth and bright—  
And this was odd, because it was  
The middle of the night.  
  
The moon was shining sulkily,  
Because she thought the sun  
Had got no business to be there  
After the day was done—  
“It’s very rude of him,” she said,  
“To come and spoil the fun!”  

## Last Verse
<!--Put a short poem of your choice 8-20 lines,here!-->
And the silken, sad, uncertain rustling of each purple curtain  
Thrilled me—filled me with fantastic terrors never felt before;  
So that now, to still the beating of my heart, I stood repeating  
“’Tis some visitor entreating entrance at my chamber door—  
Some late visitor entreating entrance at my chamber door;—  
This it is and nothing more.”  
  
Presently my soul grew stronger; hesitating then no longer,  
“Sir,” said I, “or Madam, truly your forgiveness I implore;  
But the fact is I was napping, and so gently you came rapping,  
And so faintly you came tapping, tapping at my chamber door,  
That I scarce was sure I heard you”—here I opened wide the door;—  
Darkness there and nothing more.  